### ISSUE TITLE
Wrong output given depending on capitalisation

### ISSUE THREAD

**Issue by j-bowhay** [prosegrinder/python-syllables#27]
```
In [2]: import syllables

In [3]: syllables.estimate("according")
Out[3]: 3

In [4]: syllables.estimate("according".upper())
Out[4]: 1
```

Not sure if this behaviour is intended or not but it caught me slightly by surprise.

**Comment by davidlday** [comment]
Thanks for opening this issue. Definitely not intended behavior. I'm trying to reproduce and will add this in as a test case.
